spring:
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 1000Mb
  datasource:
      name: test
      url: jdbc:mysql://localhost:3306/jlzm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: password
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  freemarker:
    cache: false
    request-context-attribute: request
    settings:
      auto_import: /spring.ftl as spring

mybatis:
  type-aliases-package: org.cloud.pestle.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql